### ISSUE TITLE
mac version unexpectedly closing

### ISSUE THREAD

**Issue by benschinn** [eul-im/eul#73]
I downloaded the mac version from the [website](https://eul.im/) and after unzipping and opening the application, the application immediately  shut down, and got an error message like so:

<img width="429" alt="screen shot 2018-03-23 at 3 51 46 pm" src="https://user-images.githubusercontent.com/21044999/37854929-8e22e828-2eb2-11e8-964c-1e0f0e442b25.png">

Has anyone else experienced this problem?

**Comment by pocketarc** [comment]
I've just had this happen to me; I can provide the error logs if needed?

**Comment by voltapp2** [comment]
Hi @schinns @BrunoDeBarros 

0.30 is very unstable. These crashes have been fixed in 0.32, which was supposed to be released 2 days ago, but there are Linux issues I need to fix first.

I hope to release it today.

**Comment by pocketarc** [comment]
Awesome! 😃 I really wish I could help, but I'm not experienced in desktop programming. Regardless, I've just pledged on Patreon to try to help you out. I love what you're doing, and the fact that it's native is by far the best part about it.

**Comment by voltapp2** [comment]
Thanks, Bruno :)

**Comment by tuananh** [comment]
@eul-im hi, is it released? the latest release from the web still crashes for me.

**Comment by jgbrwn** [comment]
Crashing as well for me.  Would love to try this out.

**Comment by BrianGilbert** [comment]
Also getting crashes on launch.. any update on when 0.32 will be available for mac?

**Comment by juancampa** [comment]
Getting the same crash. If I run it from the command line I get the following error right before the crash:

```
eul 0.31
[NSTaggedPointerString drawInRect:]: unrecognized selector sent to instance 0x500000005
```

Hope it helps

**Comment by nlassaux** [comment]
This is a pretty blocking bug, any update on that new fix? Looking forward to testing it!

**Comment by davidsielert** [comment]
yeah this sucks can't even use the app

**Comment by voltapp2** [comment]
v0.33 has just been released. Can you please try again?

**Comment by tuananh** [comment]
i got this error from 0.33
```
/Applications/eul.app/Contents/MacOS/eul ; exit;
dyld: Library not loaded: libnanovg.a
  Referenced from: /Applications/eul.app/Contents/MacOS/eul
  Reason: image not found
[1]    1662 abort      /Applications/eul.app/Contents/MacOS/eul

```

**Comment by atg** [comment]
Still crashes on 0.35 with the same error.

**Comment by voltapp2** [comment]
Sorry for the ridiculous delay.

nanovg is no longer used, so this won't be a problem anymore.
